"""Generate one rounded liquid-star mark for the app, tray and native panel."""
from PIL import Image, ImageDraw, ImageFilter
from pathlib import Path
import math
out=Path(__file__).resolve().parents[1]/'assets'
S=4
# Continuous cubic curves round every tip and valley; no square background.
segments=[((128,20),(151,20),(148,74),(169,87)),((169,87),(190,102),(236,101),(236,128)),((236,128),(236,154),(183,152),(169,169)),((169,169),(150,188),(155,236),(128,236)),((128,236),(101,236),(103,185),(87,169)),((87,169),(69,152),(20,155),(20,128)),((20,128),(20,101),(72,104),(87,87)),((87,87),(106,70),(101,20),(128,20))]
points=[]
for a,b,c,e in segments:
 for j in range(40):
  t=j/40; q=1-t
  points.append(((q**3*a[0]+3*q*q*t*b[0]+3*q*t*t*c[0]+t**3*e[0])*S,(q**3*a[1]+3*q*q*t*b[1]+3*q*t*t*c[1]+t**3*e[1])*S))
mask=Image.new('L',(256*S,256*S));md=ImageDraw.Draw(mask);md.polygon(points,fill=255)
image=Image.new('RGBA',mask.size)
pixels=image.load()
for y in range(mask.height):
 for x in range(mask.width):
  nx=x/(256*S);ny=y/(256*S)
  shine=math.exp(-((nx-.33)**2+(ny-.24)**2)/.026)
  t=min(1,max(0,.30*nx+.85*ny))
  pixels[x,y]=(int(51+69*t+95*shine),int(215-91*t+33*shine),int(177+59*t+20*shine),255)
image.putalpha(mask)
# A soft interior sheen and a thin continuous rim make the silhouette read at 16px.
rim=Image.new('RGBA',mask.size);rd=ImageDraw.Draw(rim);rd.line(points+[points[0]],fill=(231,255,251,95),width=2*S,joint='curve')
image=Image.alpha_composite(image,rim)
image=image.resize((256,256),Image.Resampling.LANCZOS)
image.save(out/'icon.png')
image.save(out/'icon.ico',sizes=[(16,16),(24,24),(32,32),(48,48),(64,64),(128,128),(256,256)])
tray=image.resize((64,64),Image.Resampling.LANCZOS);tray.save(out/'tray.png')
# Embed the same pixels so the native executable needs no external logo file.
logo=image.resize((96,96),Image.Resampling.LANCZOS)
data=list(logo.getdata())
header=['// Generated by scripts/icon.py; RGBA bytes packed as little-endian words.','#pragma once','#include <cstdint>','static constexpr int kLogoSize = 96;','static const uint32_t kLogoPixels[] = {']
for i in range(0,len(data),12):
 header.append(','.join('0x%08xu'%(r|(g<<8)|(b<<16)|(a<<24)) for r,g,b,a in data[i:i+12])+',')
header.append('};')
(out.parent/'native/glass-panel/logo_pixels.h').write_text('\n'.join(header)+'\n',encoding='utf-8')
